apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - external-secret.yaml

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.21.0
    releaseName: prometheus
    namespace: monitoring
    valuesInline:
      serverFiles:
        alerting_rules.yml:
          groups:
            - name: nexora-workloads
              rules:
                - alert: HighFraudServiceCPU
                  expr: 'sum(rate(container_cpu_usage_seconds_total{pod=~"fraud-service.*"}[1m])) > 0.8'
                  for: 1m
                  labels:
                    severity: critical
                  annotations:
                    summary: "Fraud Service CPU usage is CRITICAL (>80%)"
                    description: "Fraud Service is under heavy compute load. HPA should be triggering."

      server:
        # DURABLE STORAGE RETAINED!
        persistentVolume:
          enabled: true
          storageClass: "ebs-gp3"
          size: 8Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 2Gi
        livenessProbeInitialDelay: 60
        readinessProbeInitialDelay: 30
      alertmanager:
        enabled: true
        persistence:
          enabled: true
          storageClass: "ebs-gp3"
          size: 2Gi

        extraSecretMounts:
          - name: smtp-credentials
            mountPath: /etc/alertmanager/secrets
            secretName: alertmanager-smtp-secret
            readOnly: true

        config:
          global:
            smtp_smarthost: 'smtp.gmail.com:587'
            smtp_from: 'ahmedkhater2611@gmail.com'
            smtp_require_tls: true
          route:
            receiver: 'email-alerts'
            group_wait: 30s
            group_interval: 1m
            repeat_interval: 1h
          receivers:
            - name: 'email-alerts'
              email_configs:
                - to: 'ahmedkhater2611@gmail.com'
                  send_resolved: true
                  auth_username: 'ahmedkhater2611@gmail.com'
                  auth_password_file: /etc/alertmanager/secrets/smtp-password

      pushgateway:
        enabled: false
      nodeExporter:
        enabled: true # KEPT ENABLED!