---
# Allow the Gateway pod to receive public traffic and route to frontend & gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexora-gateway-policy
  namespace: nexora
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: nexora-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {} # Allow public ingress on port 80
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: frontend-web
      ports:
        - protocol: TCP
          port: 80
    - to:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53