apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret
  namespace: monitoring # Must be in the monitoring namespace!
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials # The Kubernetes Secret Grafana will read
    creationPolicy: Owner
  data:
    # We map the AWS JSON key to a specific key in the Kubernetes secret
    - secretKey: admin-password
      remoteRef:
        key: nexora/staging/db-credentials
        property: GRAFANA_ADMIN_PASSWORD