apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    # MergePolicy allows Kustomize to provide the username, and ESO to inject the password!
    creationPolicy: Merge
  data:
    - secretKey: admin-password
      remoteRef:
        key: nexora/staging/db-credentials
        property: GRAFANA_ADMIN_PASSWORD