apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    # 1. Pull the password dynamically from AWS Secrets Manager
    - secretKey: admin-password
      remoteRef:
        key: nexora/staging/db-credentials
        property: GRAFANA_ADMIN_PASSWORD
        
    # 2. Inject the static username directly into the secret
    - secretKey: admin-user
      remoteRef:
        key: nexora/staging/db-credentials # Dummy remoteRef
        property: GRAFANA_ADMIN_PASSWORD   # Ignored because of the template override below!
        
  # Overrides the dummy remoteRef to strictly inject the static 'admin' username
  dataFrom: []
  template:
    data:
      admin-user: "admin"