apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - external-secret.yaml

# Native Kustomize Secret Generator provides the static username!
secretGenerator:
  - name: grafana-admin-credentials
    behavior: create
    literals:
      - admin-user=admin

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 7.3.7
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin-user
        passwordKey: admin-password
      
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local
              access: proxy
              isDefault: true