apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - external-secret.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 7.3.7
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      # Tells Grafana to use our generated secret
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin-user
        passwordKey: admin-password
      
      # Automatically connects Grafana to Prometheus!
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local
              access: proxy
              isDefault: true