apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-credentials-sync
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-secret # The secret Alertmanager will mount
    creationPolicy: Owner
  data:
    - secretKey: smtp-email
      remoteRef:
        key: nexora/staging/alerting-credentials
        property: SMTP_EMAIL
    - secretKey: smtp-password
      remoteRef:
        key: nexora/staging/alerting-credentials
        property: SMTP_PASSWORD