apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-service-mesh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Nexora-Banking-App/platform-config.git'
    targetRevision: HEAD
    path: platform-manifests/istio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nexora
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
  # CRITICAL FIX: Stops the infinite out-of-sync loop on failurePolicy!
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
        - /webhooks/1/failurePolicy