apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-service-mesh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Nexora-Banking-App/platform-config.git'
    targetRevision: HEAD
    path: platform-manifests/istio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true