apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: '25.21.0'
    chart: prometheus
    helm:
      values: |
        server:
          persistentVolume:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 2Gi # <-- Increased to 2Gi so OOMKills are impossible!
          livenessProbeInitialDelay: 60
          readinessProbeInitialDelay: 30
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
        nodeExporter:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true