apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 1.6.0
    releaseName: backstage
    namespace: backstage
    valuesInline:
      # Inject configuration directly into the container's environment variables!
      extraEnvVars:
        - name: APP_CONFIG_backend_auth_dangerouslyDisableDefaultAuthPolicy
          value: "true"
        - name: APP_CONFIG_auth_environment
          value: "development"
        - name: APP_CONFIG_catalog_locations_0_type
          value: "url"
        - name: APP_CONFIG_catalog_locations_0_target
          # Direct raw YAML fetch (requires zero GitHub API tokens!)
          value: "https://raw.githubusercontent.com/Nexora-Banking-App/nexora-apps/main/catalog-info.yaml"

      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi