apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
  # 1. Grafana Loki (The Log Database)
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.41.5
    releaseName: loki
    namespace: logging
    valuesInline:
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        storage:
          type: filesystem
      singleBinary:
        replicas: 1

  # 2. FluentBit (The DaemonSet that collects logs from every node)
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.43.0
    releaseName: fluent-bit
    namespace: logging
    valuesInline:
      config:
        outputs: |
          [OUTPUT]
              Name loki
              Match *
              Host loki.logging.svc.cluster.local
              Port 3100
              Labels job=fluentbit