apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
  # 1. Grafana Loki - log database
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.41.5
    releaseName: loki
    namespace: logging
    valuesInline:
      loki:
        auth_enabled: false

        commonConfig:
          replication_factor: 1

        storage:
          type: filesystem

      singleBinary:
        replicas: 1

      # Disable tests to pass validation when self-monitoring is off
      test:
        enabled: false

      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
        lokiCanary:
          enabled: true

  # 2. Fluent Bit - collects logs from Kubernetes nodes
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.43.0
    releaseName: fluent-bit
    namespace: logging
    valuesInline:
      config:
        outputs: |
          [OUTPUT]
              Name loki
              Match *
              Host loki.logging.svc.cluster.local
              Port 3100
              Labels job=fluentbit